@url_dev = http://localhost:3055/v1/api

###
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 492e8858664566a0e7b02f2a88b90dfd7dc792e449ede17ece4fad61d64cd7a8cf564b59dea95c68a46a4efe29c7474c80af01c997f4f133834c3e331d63e2b8

{
  "name": "minh",
  "email": "minh13@gmail.com",
  "password": "securepassword"
}


###
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 492e8858664566a0e7b02f2a88b90dfd7dc792e449ede17ece4fad61d64cd7a8cf564b59dea95c68a46a4efe29c7474c80af01c997f4f133834c3e331d63e2b8

{
  "email": "minh13@gmail.com",
  "password": "securepassword"
}


###
POST {{url_dev}}/shop/handlerRefreshToken
x-api-key: 492e8858664566a0e7b02f2a88b90dfd7dc792e449ede17ece4fad61d64cd7a8cf564b59dea95c68a46a4efe29c7474c80af01c997f4f133834c3e331d63e2b8
x-client-id: 66ea50bffe72b0aa13c30f8a
x-rtoken-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVhNTBiZmZlNzJiMGFhMTNjMzBmOGEiLCJlbWFpbCI6Im1pbmgxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjY2NzI1MTMsImV4cCI6MTcyNzI3NzMxM30.TVZRHIU6in-ImXmmCG3VELg3xYGWatDHw9arLDK6_Kc



###
POST {{url_dev}}/shop/logout
x-api-key: 492e8858664566a0e7b02f2a88b90dfd7dc792e449ede17ece4fad61d64cd7a8cf564b59dea95c68a46a4efe29c7474c80af01c997f4f133834c3e331d63e2b8
x-client-id: 66ea50bffe72b0aa13c30f8a
x-rtoken-key:
authorization: 


###
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: 492e8858664566a0e7b02f2a88b90dfd7dc792e449ede17ece4fad61d64cd7a8cf564b59dea95c68a46a4efe29c7474c80af01c997f4f133834c3e331d63e2b8
x-client-id: 66ea50bffe72b0aa13c30f8a
authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVhNTBiZmZlNzJiMGFhMTNjMzBmOGEiLCJlbWFpbCI6Im1pbmgxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjcwMDIxMzksImV4cCI6MTcyNzE3NDkzOX0.COhOxjXGpAstH91ITnncbfBD3WnllM5vF4r48d63Hqo

{
  "product_name": "TShirt",
  "product_thumb": "shirt.jpg",
  "product_description": "100% cotton",
  "product_price": 99999,
  "product_type": "clothings",
  "product_quantity": 20,
  "product_attribute": {
    "brand": "N7",
    "size": "M",
    "color": "Cotton"
  }
}





